---
- name: "Check if {{ tool_name }} is installed"
  ansible.builtin.shell: "command -v {{ tool_name }}"
  register: tool_exists
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: "Install {{ tool_name }}"
  when: tool_exists.rc != 0
  block:
    - name: Get {{ tool_name }} installer
      ansible.builtin.get_url:
        url: "{{ installer_url }}"
        dest: "/tmp/{{ tool_name }}_installer.sh"
        mode: 'u+rwx'

    - name: Install {{ tool_name }}
      ansible.builtin.command: "/tmp/{{ tool_name }}_installer.sh {% for i in cmd_args %}{{ i }}{% endfor %}"

    - name: Remove the {{ tool_name }}_installer.sh
      ansible.builtin.file:
        path: "/tmp/{{ tool_name }}_installer.sh"
        state: absent
