---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: ansible_os_family == 'Darwin' or ansible_distribution == 'Ubuntu'

- name: Install Homebrew apps
  ansible.builtin.shell:
    cmd: "source {{ ansible_env.HOME }}/.zshrc && brew bundle --file={{ ansible_env.HOME }}/.config/brew/Brewfile"
    executable: /bin/zsh
  when: ansible_os_family == 'Darwin' or ansible_distribution == 'Ubuntu'
