set mouse=a

set number
set relativenumber

set cursorline
:highlight Cursorline cterm=bold ctermbg=black

set hlsearch

set tabstop=4
set softtabstop=4
set textwidth=79
set expandtab

set showmatch

set termguicolors
colorscheme desert

syntax on
set lcs=space:·
set list

filetype plugin indent on

call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-commentary'
Plug 'preservim/nerdtree'
call plug#end()

noremap <leader>w :w<CR>
noremap <leader>q :q<CR>
xnoremap v iw
xnoremap p pgvy

nnoremap <C-t> :NERDTreeToggle<CR>
